spring.application.name=demo

# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/music_school
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? Hibernate (JPA)

spring.jpa.hibernate.ddl-auto=update

# ????? SQL-???????? ? ???????
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
